### ISSUE TITLE
Integrating random Vert color per loose parts, plus gradient tool

### ISSUE THREAD

**Issue by JoseConseco** [andyp123/blender_vertex_color_master#1]
Could you integrate those two operators into vert color master?
File with python operators:
[https://www.dropbox.com/s/znq2b41csgrbhbd/VertOperators.py?dl=0](https://www.dropbox.com/s/znq2b41csgrbhbd/VertOperators.py?dl=0)
 I'm author for both of these

**Comment by andyp123** [comment]
Thanks for the suggestion, Jose. I will definitely have a look at this as soon as I can. I'll try to get it done before the end of the month, but if it looks like it won't take long, maybe I can do it much sooner.

**Comment by andyp123** [comment]
These features are now properly merged and I added a few other bits, like masking support for them and a new HSV adjust tool.
