### ISSUE TITLE
Suggestion: Moving to Paint Tab

### ISSUE THREAD

**Issue by dval** [andyp123/blender_vertex_color_master#19]
This tool is awesome.
On my install I made a change to vcm_menus.py, and changed the location from 'View' to 'Paint'.

`line 37:     bl_category =  'Paint'`

This makes my color palette readily available. And Paint Tab is less crowded so there is less visual clutter.

https://imgur.com/a/1CYvtj3

Just a suggestion.

**Comment by andyp123** [comment]
You are totally right. I don't know why I put it in the view tab in the first place. I'll try to update soon.

**Comment by andyp123** [comment]
I just realised that I already moved it to its own VCM tab. In order to get Vertex Color Master to appear in any tab in vertex paint mode you can just pin it (right click and check the pin box, or shift click the header).
