### ISSUE TITLE
BUG: Keymap doesn't unregister correctly

### ISSUE THREAD

**Issue by andyp123** [andyp123/blender_vertex_color_master#23]
The key for pie menus can't be unregistered properly, which sometimes causes errors on script reload and addon uninstallation.

Traceback (most recent call last):
  addon_utils.py, line 437, in disable
    mod.unregister()
 __init__.py, line 113, in unregister
    del bpy.types.Scene.vertex_color_master_settings
AttributeError: 'tuple' object has no attribute 'keymap_items'

**Comment by flexchan2012** [comment]
Referring to Blender manual[ Here](https://docs.blender.org/manual/en/latest/advanced/scripting/addon_tutorial.html#keymap) Maybe you can try this unregister func
```
def unregister():
    ...
    # unregister shortcuts
    wm = bpy.context.window_manager
    if wm.keyconfigs.addon:
        for km,kmi in addon_keymaps:
            km.keymap_items.remove(kmi)
        wm.keyconfigs.addon.keymaps.remove(km)
    addon_keymaps.clear()
```

**Comment by andyp123** [comment]
Thanks for the suggestion! I think that's where I got the original code from, but it could have been updated since. I haven't been keeping this addon updated recently, but I may return to it now Blender 3.0 is out and the vertex colour editing mode isn't going to change drastically any time soon.

**Comment by andyp123** [comment]
Fixed :)
