### ISSUE TITLE
0.85 v dosent work in Blender 2.9

### ISSUE THREAD

**Issue by Carlos3D** [andyp123/blender_vertex_color_master#32]
I try several times to install without success.

**Comment by enzyme69** [comment]
Try using Blender 2.92 install SV there. Blender 2.93 does not work at the moment.

**Comment by danocox** [comment]
Tried on my end too in 2.92 and same result

**Comment by marquismiller** [comment]
Please let this be a possible tool in the latest updates in Blender. I need this lol.

**Comment by andyp123** [comment]
Although there are bugs, the addon can be installed and works for me in the latest version of Blender (3.3) and I haven't had problems installing it in earlier releases, so I'm going to close this bug for now.
