### ISSUE TITLE
Isolate mode not working correctly

### ISSUE THREAD

**Issue by andyp123** [andyp123/blender_vertex_color_master#39]
When switching to isolate mode, a new channel is created, but Blender does not switch to viewing it. This seems to have occurred around Blender 3.2

**Comment by soy1bonus** [comment]
Wow, I didn't expect you to go back to this project! There is no other addon like this one and I use it almost everyday. Thanks a lot beforehand!

**Comment by koffeinvampir** [comment]
Yep, same issue here in Blender 3.2 and working fine in 3.1. If there's anything that helps you get ahead of the issue, I'll happy to help. 👍

**Comment by EtienneVanier** [comment]
Same issue in 3.3. Hope you'll have the time to fix this, your plugin extends Blender's functions in an essential manner. Thank you for your work.

**Comment by unfa** [comment]
I've discovered this add-on recently and it'd make my life  way easier if it worked as intended with Blender 3.2.

Things I am trying to do is apply Dirty Vertex Colors (AO) on one of the channels only, and then invert that. Unfortunately it doesn't work as expected.

**Comment by andyp123** [comment]
I keep thinking I'm going to fix these issues and then not doing it, but I have some time off work right now, so I'll look into it.

Thank you very much for the donation. I'll try to get these issues fixed up as soon as I can.

**Comment by j-conrad** [comment]
Just adding my voice to help encourage you, @andyp123 . I use this add-on and continue to suggest it to other Blender users regularly.
Thank you!

**Comment by berdel04** [comment]
great to see you reactivated this project! Blenders vertex painting is still super basic

**Comment by stianhje** [comment]
Would be amazing if this great add-on would be updated. I've using it actively since 2019 and I love it.

**Comment by Moerti84** [comment]
I can only agree. It was working fine up to 3.2 and made my life so much easier. This is almost a must for game artist, I would say. Me and I guess many others would really appreciate an update.

**Comment by andyp123** [comment]
Really sorry for how long it's taking me to take a look at this issue. I'm just having a look at it now, but not immediately sure what is going on. It seems to be something in Blender itself that might not be behaving correctly, as it seems to report the active vertex colour layer incorrectly sometimes. I will do some more investigation and if I can't figure it out I'll ask the Blender dev behind the recent vertex colour > attributes changes to take a look.

Temporary workaround:
1. Isolate a vertex colour channel in VCM.
2. Open object data properties and fold down the "Color Attributes" panel.
4. Select the isolated colour layer (will be named VCM-ISO_<Channel>_<Layer Name>)
From now on, pressing isolate, apply and discard should work more or less correctly FOR THAT OBJECT, though you may still run into problems if you are using many layers. Unfortunately, you'll need to do this for every object you are working with.

**Comment by michaeldll** [comment]
I'm having the isolated Vertex Color issue on 3.2 onwards as well.
I therefore add my voice to the others to encourage you to fix these issues, we use your addon almost every day at my WebGL agency <3

**Comment by andyp123** [comment]
Should be working in the [current pre-release supporting 4.0+](https://github.com/andyp123/blender_vertex_color_master/releases/tag/v0.9.0alpha)

**Comment by michaeldll** [comment]
Thank you so much
