### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Andrej730** [andyp123/blender_vertex_color_master#40]
The last release was 15 oct 2019 and since some bugs were fixed relatively recently - I think it could be good time for creating new release.

**Comment by jaston559** [comment]
Yes with the change from vertex color to now color attributes this add-on no longer works in 3.2 onward. I would love to see this addon updated as well.

**Comment by Andrej730** [comment]
> Yes with the change from vertex color to now color attributes this add-on no longer works in 3.2 onward. I would love to see this addon updated as well.

can you please give some example of not working features?

**Comment by DmitriyBerezovskiy** [comment]
Hi! There are problems in Blender 3.4. The "Adjust HSV" operation doesn't work correctly:

https://user-images.githubusercontent.com/122796254/212685322-f0d31ae4-61cd-4365-bb6f-f194b1fae9b9.mp4

Blender 3.2 in the same scene - everything is fine

https://user-images.githubusercontent.com/122796254/212686362-6c9ae998-8242-4c8b-b595-41e03565a220.mp4

Maybe I'm doing something wrong.. VCM version is 0.84:

![image](https://user-images.githubusercontent.com/122796254/212687541-d6d36b1c-c1f9-42f3-9954-fa3792b05032.png)

Pay attention, please. Thank you! =)

**Comment by SophieRefshauge** [comment]
I am also having the same issues with the Adjust HSV - would love to see this updated to work for Blender 3.4!
This is a wonderful add-on

**Comment by andyp123** [comment]
[Pre-release here](https://github.com/andyp123/blender_vertex_color_master/releases/tag/v0.9.0alpha). Unfrotunately Adjust HSV is not working because of issues with the redo panel. I'm not sure how I can fix this :(

**Comment by Andrej730** [comment]
@andyp123 hi! Can you please pin this pre-release on the main page? I believe this is the way most of the users will try to download it but it won't work.

![image](https://github.com/user-attachments/assets/4da50e12-8d9c-4322-af8d-3827440718f4)

**Comment by andyp123** [comment]
I didn't check that, but good catch.
