### ISSUE TITLE
Does not work in blender 4.0.0

### ISSUE THREAD

**Issue by mpetrikov** [andyp123/blender_vertex_color_master#42]
When I try to turn on the plugin, installed from vertex_color_master-v084.zip, then the following error appears

![image](https://github.com/andyp123/blender_vertex_color_master/assets/3761652/00e75880-36e3-4311-bd86-b1c60402d24c)

**Comment by Andrej730** [comment]
Fixed issue on the addon ork - https://github.com/Andrej730/blender_vertex_color_master

**Comment by Andrej730** [comment]
@MilkBoyG you're talking about the different error than described in this issue.

Are you sure installed the addon correctly? I have another PR adding more precise instruction on installation from github repository #44 (you can lookup the instructions there).

**Comment by MilkBoyG** [comment]
> @MilkBoyG you're talking about the different error than described in this issue.
> 
> Are you sure yiu installed the addon correctly? I have another PR adding more precise instruction on installation from github repository #44 (you can lookup the instructions there).

Got it working! So the issue was that the zip had nested folders.

**Comment by andwhatisgenerallyavailable** [comment]
not installed
![1](https://github.com/andyp123/blender_vertex_color_master/assets/150661200/c0a06847-ac00-4915-9a41-07be9e575bab)

**Comment by Andrej730** [comment]
@andwhatisgenerallyavailable see my comment above - https://github.com/andyp123/blender_vertex_color_master/issues/42#issuecomment-1817567620

**Comment by andwhatisgenerallyavailable** [comment]
I didn't understand something. That's where I downloaded it.

**Comment by Andrej730** [comment]
> I didn't understand something. That's where I downloaded it.
The fork doesnt have that line of code that's mentioned in your error log, so you must've been using a different version.

**Comment by andwhatisgenerallyavailable** [comment]
I don’t understand, what should I do? your link leads to the addon. I downloaded it. it doesn't work. I downloaded it a second time, it doesn't work the second time. I don't understand what to do.

**Comment by Andrej730** [comment]
@andwhatisgenerallyavailable how you installed it? If you've just downloaded the zip-file from github and intalled as blender addon then it won't work. Try this instruction - https://github.com/andyp123/blender_vertex_color_master/pull/44/files

**Comment by andwhatisgenerallyavailable** [comment]
it says that I need to replace the contents of the motherboard here `C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\x.x\scripts\addons\vertex_color_master\`. to the contents of the downloaded folder. but this is my first time installing an addon, my blender folder is empty. I tried to create such a folder and install it in it, but it did not help, so blender does not see the addon at all.

**Comment by Andrej730** [comment]
@andwhatisgenerallyavailable it cannot be empty, error log is telling that previously installed addon is there.
![image](https://github.com/andyp123/blender_vertex_color_master/assets/9417531/94a496e0-22d5-4728-a578-41f27892a538)

**Comment by andwhatisgenerallyavailable** [comment]
maybe I don't understand. I recorded a video. The addon does not install even if I follow those instructions.
https://drive.google.com/drive/folders/18WVdosl3SkTtZtL5iTquXkEQ3UPU_sGa?usp=drive_link

**Comment by Andrej730** [comment]
@andwhatisgenerallyavailable I think you've done everything right except you've installed broken version
https://github.com/andyp123/blender_vertex_color_master/archive/refs/heads/master.zip
instead of the fixed version
https://github.com/Andrej730/blender_vertex_color_master/archive/refs/heads/master.zip

**Comment by andwhatisgenerallyavailable** [comment]
that's right, now it works. Thank you!

**Comment by speeddial6** [comment]
i have tried everything and i still cant get it to work

**Comment by Andrej730** [comment]
> i have tried everything and i still cant get it to work

what error?

**Comment by speeddial6** [comment]
when i try to download it normally i encounter the same error that started this thread but i tried using the more advanced instructions that you said the other people should follow but it still doesnt work it doesnt show up at all in the addons list and i restart blender

**Comment by Andrej730** [comment]
@andyp123 can you please describe step by step some way you tried? You can use the zip archive from this repository (NOT the release) https://github.com/andyp123/blender_vertex_color_master/archive/refs/heads/master.zip, it should work.

**Comment by speeddial6** [comment]
so i go into the vertex_colour_master folder inside the blender_vertex_color_master-master and then i copy the files inside the vertex_colour_master folder and go into the addons folder and inside the addons folder there is a blender_vertex_color_master-master folder and i go into that and paste the files from the download zip into the vertex_colour_master folder

**Comment by Andrej730** [comment]
> so i go into the vertex_colour_master folder inside the blender_vertex_color_master-master folder and then i copy the files inside the vertex_colour_master folder and go into the addons folder and inside the addons folder there is a blender_vertex_color_master-master folder and i go into that and paste the files from the download zip into the vertex_colour_master folder then i restart blender


there should be just `vertex_color_master` folder inside `addons` (not inside `blender_vertex_color_master-master`) that will contain `__init__.py` and other files.

**Comment by speeddial6** [comment]
so should i just remove the vertex_color_master folder and remove it from blender_vertex_color_master-master folder and put it inside addon then just delete the  blender_vertex_color_master-master folder

**Comment by Andrej730** [comment]
> so should i just remove the vertex_color_master folder and remove it from blender_vertex_color_master-master folder and put it inside addon then just delete the blender_vertex_color_master-master folder

yes. The most important thing that there will be a structure like so: `addons/vertex_color_master/__init__.py` then Blender will recognize it

**Comment by speeddial6** [comment]
oh it worked now

**Comment by speeddial6** [comment]
wait no it doesnt work
it says that it is ticked  in the addons tab but doesnt show on the side where u can use ur addons

**Comment by Andrej730** [comment]
> it says that it is ticked in the addons tab but doesnt show on the side where u can use ur addons

Please show a screenshot and check system console for errors (Window -> Toggle System Console).

**Comment by andyp123** [comment]
Hi. Sorry for the addon being broken for so long. I've uploaded an [0.9.0 alpha release](https://github.com/andyp123/blender_vertex_color_master/releases/tag/v0.9.0alpha) that should work on Blender 4.0+. Note that there are some bugs, most notably that the redo panel does not work properly for many operations. Undo seems to be fine though.

**Comment by JimC-AA** [comment]
So glad to see this being resurrected. I appreciate your persistence @andyp123 ! You probably didn't even know just how many folks needed this in their workflow.

**Comment by speeddial6** [comment]
i still cant get the new version to work on 4.2 or 4.0

**Comment by Andrej730** [comment]
> i still cant get the new version to work on 4.2 or 4.0

What's the issue? Same as before - "it says that it is ticked in the addons tab but doesnt show on the side where u can use ur addons"?

**Comment by speeddial6** [comment]
yes

**Comment by Andrej730** [comment]
> Please show a screenshot and check system console for errors (Window -> Toggle System Console).

**Comment by speeddial6** [comment]
![image](https://github.com/user-attachments/assets/dafc36fb-5dc6-4f60-a148-f7434925836b)

**Comment by Andrej730** [comment]
I mean screenshot of what panel you're referring to "show on the side where u can use ur addons".

Are you sure you have some object selected and you're in vertex paint mode?

**Comment by speeddial6** [comment]
ohhhh.....

**Comment by andyp123** [comment]
There's a[ recent alpha release](https://github.com/andyp123/blender_vertex_color_master/releases/tag/v0.9.0alpha) of this addon that should allow the addon to work properly with Blender 3.6 and above. Closing this issue.
