### ISSUE TITLE
Isolated Blue channel saves in Red channel on 4.1+

### ISSUE THREAD

**Issue by LadTy** [andyp123/blender_vertex_color_master#50]
Hi, I am using the latest fork from Andrej730 https://github.com/Andrej730/blender_vertex_color_master/tree/master (the only one working on Blender 4+), it worked well on 4.0 but since 4.1+ there is an issue that Blue isolated channel is being saved in Red instead.

Steps to reproduce:
Cube (or any other model) -> Edit Mode -> Select vertices
Vertex Paint-> Vertex Selection
VCM -> Fill with Color (Black to clear all vertex color)
B -> Isolate Active Channel -> Fill With Value 1.00 (To make them 100% Blue) -> Apply Changes
Now the vertices are Red instead of Blue.

**Comment by andyp123** [comment]
Thanks for the report. I will look into this as I'm trying to do a rewrite now.

**Comment by andyp123** [comment]
This issue should be fixed in the [latest pre-release](https://github.com/andyp123/blender_vertex_color_master/releases/tag/v0.9.0alpha).
